### ISSUE TITLE
why u add three [MASK] before answer?

### ISSUE THREAD

**Issue by freeman-1995** [TencentARC/MCQ#7]

**Comment by geyuying** [comment]
It is kind of prompt learning for phrase representation. Since TextFormer is trained with full sentences, it fails to encode accurate representations for phrases when it takes a single noun or verb phrase as the input due to the lack of context. Motivated by the success of prompt engineering, we add “[MASK]” before the noun and verb phrase (e.g. “[MASK] [MASK]
[MASK] green grass”) to extract noun or verb representations from TextFormer. We show ablation studies of the
prompt “[MASK]” for noun and verb representations in Table. 9. You can refer to Table 9 in our paper https://arxiv.org/pdf/2201.04850.pdf for details.

**Comment by freeman-1995** [comment]
ok, thanks
